apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura-service
spec:
  selector:
    app: conversao-temperatura
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura-deploy
  labels:
    app: conversao-temperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: sinayra/conversao-temperatura:v1
        ports: 
          - containerPort: 8080

